# This file controls the settings for your Quarto template. Modified from www.marvinschmitt.com\

  # Notes:
    # If you have trouble rendering, delete the docs folder (you can't break it - it regenerates every time you render)
    # Index.qmd is how you test the website - Render this to try
    # There are folders for each of the directories up the top in the banner
    # Better to put photos in each proejct folder

# website settings
website:
  title: "Alice Pidd"  # Your name
  description: "Alice is a PhD student at USC"   # A brief slogan (optional)
  image: img/NZ2023_1.jpg # Photo of yourself from the img folder within this proj
  
  favicon: img/icon1.png # Logo or icon for the website, same as firefox or other website logos you see in a tab
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true # Navbar will be stuck at the top
    logo: /img/icon1.png # Logo to the left of the navbar
    
    # your sub-pages
    left: # Justified to the left of the 
      # - text: "Projects" # Name that's displayed
      #   href: projects/index.qmd # Folder for where to find the info
      - text: "Current projects" 
        href: current_projects/index.qmd # Website address/hyperlink

      # - text: "Blog" 
      #   href: posts.qmd 
      # - text: "Photography" 
      #   href: photography/index.qmd 
      - text: "CV" 
        href: cv/index.qmd 
      - text: "Publications" 
        href: https://scholar.google.com.au/citations?user=2nZwCKEAAAAJ&hl=en
        target: _blank 
    
    # your social media handles
    right:
      # - icon: linkedin
      #   href: https://www.linkedin.com/XXXX
      - icon: envelope
        aria-label: email
        href: "mailto:alicempidd@gmail.com"  
      - icon: github
        href: https://github.com/AlicePidd
      - icon: twitter
        href: https://twitter.com/alicempidd
        

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    # left: |
    #   <span class="faux-block">&#169; 2024 Gandalf the White CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/AlicePidd/alicepidd.github.io">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: false

format:
  html:
    fontsize: 1.1em
    theme: 
      # - Slate # Website theme !!!!
      - Lux
      # - Solar
      # - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
